name = "maparchive-web"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist/client"

# wrangler d1 create archive-db

# [[d1_databases]]
# binding = "DB"
# database_name = "archive-db"
# database_id = ""

# [[r2_buckets]]
# binding = "R2"
# bucket_name = "ciesin-dev"
