"""
Summarize admin units from file_list CSV generated by countGoogleDriveFiles.py

This script analyzes the file_list CSV and provides counts of unique admin units
at each administrative level (admin0/province through admin4).
"""

import csv
import sys
from pathlib import Path
from collections import defaultdict, Counter
import argparse


def load_province_dictionary(dict_path=None):
    """
    Load province dictionary for standardized names.
    Returns a dict mapping cleaned province names to province details.
    """
    if dict_path is None:
        # Default path relative to this script
        script_dir = Path(__file__).parent.parent
        dict_path = script_dir / 'dictionary' / 'rdc_provinces.csv'
    
    province_dict = {}
    try:
        with open(dict_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Key by cleaned name for matching
                province_dict[row['province_cleaned']] = row
        print(f"✓ Loaded {len(province_dict)} provinces from dictionary")
    except FileNotFoundError:
        print(f"⚠ Warning: Province dictionary not found at {dict_path}")
    except Exception as e:
        print(f"⚠ Warning: Could not load province dictionary: {e}")
    
    return province_dict


def extract_province_from_folder(folder_path):
    """
    Extract province name from folder path.
    Assumes structure like: "Project_Extension.../KASAI/..." or "MANIEMA/..."
    """
    if not folder_path:
        return None
    
    # Split by '/' and look for province names (typically uppercase)
    parts = folder_path.split('/')
    for part in parts:
        # Province names are typically uppercase and meaningful
        if part.isupper() and len(part) > 2:
            return part
    
    return None


def tally_admin_units(csv_path, province_dict=None):
    """
    Count unique admin units at each level from the file_list CSV.
    
    Args:
        csv_path: Path to the file_list CSV
        province_dict: Optional dictionary of province information
        
    Returns:
        dict with counts and details for each admin level
    """
    # Counters for each admin level
    admin_counts = {
        'admin0': Counter(),  # Province
        'admin1': Counter(),  # TODO: Placeholder for admin1
        'admin2': Counter(),  # TODO: Placeholder for admin2
        'admin3': Counter(),  # TODO: Placeholder for admin3
        'admin4': Counter(),  # TODO: Placeholder for admin4
    }
    
    # Track provinces from folder paths
    provinces_from_folder = Counter()
    
    # Stats
    total_files = 0
    parsed_files = 0
    unparsed_files = 0
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            total_files += 1
            
            # Check if filename was successfully parsed
            if row.get('parsed') == 'True':
                parsed_files += 1
                
                # Count admin units from parsed filename
                if row.get('admin0'):
                    admin_counts['admin0'][row['admin0']] += 1
                if row.get('admin1'):
                    admin_counts['admin1'][row['admin1']] += 1
                if row.get('admin2'):
                    admin_counts['admin2'][row['admin2']] += 1
                if row.get('admin3'):
                    admin_counts['admin3'][row['admin3']] += 1
                if row.get('admin4'):
                    admin_counts['admin4'][row['admin4']] += 1
            else:
                unparsed_files += 1
            
            # Also extract province from folder path (backup method)
            province_from_folder = extract_province_from_folder(row.get('folder', ''))
            if province_from_folder:
                provinces_from_folder[province_from_folder] += 1
    
    return {
        'admin_counts': admin_counts,
        'provinces_from_folder': provinces_from_folder,
        'total_files': total_files,
        'parsed_files': parsed_files,
        'unparsed_files': unparsed_files
    }


def write_csv_summary(results, output_path, province_dict=None):
    """Write admin unit tallies to CSV file."""
    
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        
        # Write header
        writer.writerow(['admin_level', 'unit_code', 'unit_name_fr', 'unit_name_en', 'file_count'])
        
        # Admin0 (Province) - from parsed filenames
        admin0_counts = results['admin_counts']['admin0']
        for province, count in admin0_counts.most_common():
            if province_dict and province in province_dict:
                province_info = province_dict[province]
                name_fr = province_info['province_fr']
                name_en = province_info['province_eng']
            else:
                name_fr = province
                name_en = province
            
            writer.writerow(['admin0', province, name_fr, name_en, count])
        
        # Admin1-4 placeholders (write if data exists)
        for level in ['admin1', 'admin2', 'admin3', 'admin4']:
            counts = results['admin_counts'][level]
            for unit, count in counts.most_common():
                writer.writerow([level, unit, unit, unit, count])


def print_summary(results, province_dict=None):
    """Print a formatted summary of the admin unit tallies."""
    
    print("\n" + "="*70)
    print("ADMIN UNIT SUMMARY")
    print("="*70)
    
    print(f"\nTotal files analyzed: {results['total_files']:,}")
    print(f"  ├─ Parsed filenames: {results['parsed_files']:,}")
    print(f"  └─ Unparsed filenames: {results['unparsed_files']:,}")
    
    # Admin0 (Province) Summary
    print("\n" + "-"*70)
    print("ADMIN0 (PROVINCE) - From Parsed Filenames")
    print("-"*70)
    
    admin0_counts = results['admin_counts']['admin0']
    if admin0_counts:
        print(f"\nUnique provinces: {len(admin0_counts)}")
        print(f"\nProvince breakdown:")
        for province, count in admin0_counts.most_common():
            # Look up full province name if dictionary available
            if province_dict and province in province_dict:
                province_info = province_dict[province]
                display_name = f"{province_info['province_fr']} ({province})"
            else:
                display_name = province
            
            print(f"  {display_name:40s} {count:6,} files")
    else:
        print("  (No admin0 data found in parsed filenames)")
    
    # Province from folder paths
    print("\n" + "-"*70)
    print("PROVINCES - From Folder Paths (Validation)")
    print("-"*70)
    
    folder_provinces = results['provinces_from_folder']
    if folder_provinces:
        print(f"\nUnique provinces: {len(folder_provinces)}")
        print(f"\nProvince breakdown:")
        for province, count in folder_provinces.most_common():
            # Look up full province name if dictionary available
            if province_dict and province in province_dict:
                province_info = province_dict[province]
                display_name = f"{province_info['province_fr']} ({province})"
            else:
                display_name = province
            
            print(f"  {display_name:40s} {count:6,} files")
    else:
        print("  (No province data extracted from folder paths)")
    
    # Placeholders for other admin levels
    for level in ['admin1', 'admin2', 'admin3', 'admin4']:
        print("\n" + "-"*70)
        print(f"{level.upper()} - TODO: Not yet implemented")
        print("-"*70)
        
        counts = results['admin_counts'][level]
        if counts:
            print(f"\nUnique {level} units: {len(counts)}")
            print(f"(Top 5: {', '.join([f'{k} ({v})' for k, v in counts.most_common(5)])})")
        else:
            print(f"  (No {level} data found)")
    
    print("\n" + "="*70 + "\n")


def main():
    parser = argparse.ArgumentParser(
        description='Tally admin units from file_list CSV',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use most recent file_list in output folder
  python tally_admin.py
  
  # Specify a particular file_list CSV
  python tally_admin.py --csv output/file_list_2025_20260115_152454.csv
  
  # Use a custom province dictionary
  python tally_admin.py --dict ../dictionary/custom_provinces.csv
        """
    )
    
    parser.add_argument(
        '--csv',
        help='Path to file_list CSV (default: most recent in output/ folder)',
        default=None
    )
    
    parser.add_argument(
        '--dict',
        help='Path to province dictionary CSV (default: ../dictionary/rdc_provinces.csv)',
        default=None
    )
    
    args = parser.parse_args()
    
    # Determine CSV path
    if args.csv:
        csv_path = Path(args.csv)
    else:
        # Find most recent file_list in output folder
        script_dir = Path(__file__).parent.parent
        output_dir = script_dir / 'output'
        
        if not output_dir.exists():
            print(f"Error: Output directory not found: {output_dir}")
            sys.exit(1)
        
        # Find all file_list CSVs
        file_lists = list(output_dir.glob('file_list_*.csv'))
        
        if not file_lists:
            print(f"Error: No file_list_*.csv found in {output_dir}")
            sys.exit(1)
        
        # Get most recent by modification time
        csv_path = max(file_lists, key=lambda p: p.stat().st_mtime)
        print(f"Using most recent file_list: {csv_path.name}")
    
    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}")
        sys.exit(1)
    
    # Load province dictionary
    province_dict = load_province_dictionary(args.dict)
    
    # Perform analysis
    print(f"\nAnalyzing: {csv_path}")
    results = tally_admin_units(csv_path, province_dict)
    
    # Determine output path
    script_dir = Path(__file__).parent.parent
    output_dir = script_dir / 'output'
    output_dir.mkdir(exist_ok=True)
    output_csv = output_dir / 'adminTally.csv'
    
    # Write CSV summary
    write_csv_summary(results, output_csv, province_dict)
    print(f"\n✓ Admin tally saved to: {output_csv}")
    
    # Print summary to terminal
    print_summary(results, province_dict)


if __name__ == '__main__':
    main()
